apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.trtCache.pvcName }}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.trtCache.size }}
